### ISSUE TITLE
Wiki Typo 

### ISSUE THREAD

**Issue by nathanhack** [myitcv/immutable#55]
I was reading the immutable documentation and I believe the following is a typo.

```
   // NewTMapCap returns an immutable map with capacity l.
   //
   NewTMapCap(l int) *T
```

Should be:
```
   // NewTCap returns an immutable map with capacity l.
   //
   NewTCap(l int) *T
```

**Comment by myitcv** [comment]
Thanks @nathanhack - fixed as of https://github.com/myitcv/immutable/wiki/immutableGen/2c699984e178e40d3e760543217027f8c1def007
